repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        entry: make lint
        language: system
        types: [python]

      - id: type-check
        name: Type check
        entry: make typecheck
        language: system
        types: [python]
